export const FETCH_ROUTES_REQUEST = 'FETCH_ROUTES_REQUEST';
export const FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS';
export const FETCH_ROUTES_FAILURE = 'FETCH_ROUTES_FAILURE';

export const SORT_ROUTES_REQUEST = 'SORT_ROUTES_REQUEST';
export const SORT_ROUTES_SUCCESS = 'SORT_ROUTES_SUCCESS';
export const SORT_ROUTES_FAILURE = 'SORT_ROUTES_FAILURE';

export const FETCH_DELIVERY_DEPS_REQUEST = 'FETCH_DELIVERY_DEPS_REQUEST';
export const FETCH_DELIVERY_DEPS_SUCCESS = 'FETCH_DELIVERY_DEPS_SUCCESS';
export const FETCH_DELIVERY_DEPS_FAILURE = 'FETCH_DELIVERY_DEPS_FAILURE';

export const MOVE_WAYPOINT = 'MOVE_WAYPOINT';
export const TOGGLE_OPEN_ROUTE = 'TOGGLE_OPEN_ROUTE';
export const SET_CHECKED_ROUTE = 'SET_CHECKED_ROUTE';

export const SET_ACTIVE_ROUTE = 'SET_ACTIVE_ROUTE';
export const SET_ACTIVE_WAYPOINT = 'SET_ACTIVE_WAYPOINT';
export const BEGIN_LOADING = 'BEGIN_LOADING';
